apiVersion: v1
kind: Service
metadata:
  name: main-api
  labels:
    name: main-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: main-api
