apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: main-api-deployment
spec:
  selector:
    matchLabels:
      app: main-api
  replicas: 1
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
      - name: main-api
        image: gcr.io/spy-crowd/main-api:0.9.0
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.2"
        ports:
        - containerPort: 5000
